name: Build EXE with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas numpy dash plotly gensim scikit-learn spacy pyLDAvis
        python -m spacy download en_core_web_sm

    - name: Build EXE
      run: |
        pyinstaller --onefile --add-data "data;data" --add-data "model;model" app.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@master
      with:
        name: built-exe
        path: dist/app.exe
